baseURL = "https://blog.jesterlabs.ai/"
languageCode = "en-us"
title = "Jester Labs"
theme="archie"
copyright = "© Jester Labs"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	# subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	# customcss = ["css/styles.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jesterlabs"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jesterlabs_ai/"

# Main menu Items

[[menu.main]]
name = "Blog Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4